services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sipub_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
